namespace MonoGame.Common.Enums
{
    public enum ObjectEvent
    {
        Ignore,
        CollisionEnter,
        CollisionExit,
        HealthRemoved,
        HealthEmpty,
        HealthReset,
        Fire,
        AmmoRemoved,
        AmmoEmpty,
        AmmoReset,
        ElectricalFire,
        ScoreIncrease,
        ScoreIncreaseDisplay,
        InAir,
        OnWave,
        RemoveEntity,
        ResetEntity,
        NextCharacter,
        PreviousCharacter,
        NextItem,
        PreviousItem,
        MoveUp,
        MoveDown,
        MoveLeft,
        MoveRight
    }
}
